# Generated by Django 4.0.4 on 2022-05-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_time', models.DateTimeField()),
                ('Ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.field')),
                ('TeamA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamA', to='core.team')),
                ('TeamB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamB', to='core.team')),
            ],
        ),
    ]
