# Generated by Django 4.0.4 on 2022-05-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fixture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='Date_time',
        ),
        migrations.AddField(
            model_name='fixture',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='Time',
            field=models.TimeField(null=True),
        ),
    ]
