# Generated by Django 4.0.4 on 2022-05-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_fixture_date_time_fixture_date_fixture_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='Date',
            field=models.DateField(help_text='dd//mm//yy', null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='Time',
            field=models.TimeField(help_text='Ex:02:00', null=True),
        ),
    ]
