# Generated by Django 4.0.4 on 2022-05-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='Booked',
            field=models.BooleanField(default=False),
        ),
    ]
