# Generated by Django 4.0.4 on 2022-05-27 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_fixture_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('ticket_no', models.PositiveIntegerField(default=0)),
                ('persons', models.PositiveIntegerField(default=0)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fixture')),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
